### ISSUE TITLE
cannot set map zoom

### ISSUE THREAD

**Issue by valleymanbs** [toepoke/mapsed#2]
The map is always showing with maximum zoom, even if I change DEFAULT_ZOOM in mapsed.js or if I give a zoom parameter to the mapOptions when calling $("map_container").mapsed()

**Comment by drkrtj** [comment]
Hello,
   First of all I think your plugin is great. I am a newbie to javascript and jquery so I am not a ninja like all of you are currently. I have three questions or problems that I need to fix if you can help.

1.    I am trying to set the initial loaded zoom at 2 (DEFAULT_ZOOM) and the search result zoom to 4. Is this possible? The default zoom is easy to set with your instructions but once you search a location it drops you too close. I would like it to be slightly backed away.

2.    So far I have been using only the example 5 due to the search features. I would like to use all the examples which I am assuming is your "full example 6" so I can add the "custom places" features. I can not get your full example 6 to open in a small container (small-map) like your other examples so one can search in a compact window with the option of going full screen (Toggle Fullscreen View). Is there a way (or am I just doing something wrong) to allow me to put "custom place" features into this same small window along with your search features?

3.    For some reason I cannot get the "more" button to function. I know I am just doing something wrong here. I can search something like mcdonalds and it will give me only a handful of results. The more button is blue but not responsive on click. What do I need to do to get it to operate?

          Thanks for the great plugin and your help!

**Comment by toepoke** [comment]
Hi,

1) Once you search it narrows down to show all locations you've found.  I can't recall if it's Google that sets the zoom or it's in the plugin.  I'd suggest experimenting with the code locally.

2) Example 6 uses full-screen mode because it doesn't call mapsed via a selector, see:
https://github.com/toepoke/mapsed/blob/7f91e764baa4d20f0c8e2b773d1a0aa86d28d290/examples/06-full-example.js#L115

Where as example 5 does use a selector:
https://github.com/toepoke/mapsed/blob/7f91e764baa4d20f0c8e2b773d1a0aa86d28d290/examples/05-search-for-places-example.js#L2

You just need to adjust example 6 to use a selector as per example 5.

3) The "more" button only becomes active if there are more results to display.  This information comes from Google Maps search.  If there are no more hits the button is disabled.  If there are more results it's available to be clicked.

Good luck.
